name: dev-cat-jjal-maker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: npm install
        run: npm install gh-pages

      - name: Build and Deploy
        run: |
          npm run build
          enpm run deploy
