# Workflow 이름
name: dev-cat-jjal-maker            
# Event 감지
on: 
  push:
    branches: [main]                            
# Job 설정
jobs:                                
  # Job 이름
  build:                
   # Job 가상환경 인스턴스
    runs-on: ubuntu-latest           
    # Step 설정
    steps:                          
      # checkout actions 사용
      - name: Checkout
        uses: actions/checkout@main
      # 빌드
      - name: Build
        run: npm run build    
      # 디플로이
      - name: Github-Deploy
        run: npm run deploy                
